Feature/hdf 86 create getter setter
HaloDAO/halo-rewards pull request #15
Opened 2021-04-20 18:37 UTC by ernestpascual

## Description of Changes

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-)

## How To Test

### Developer Checklist:

- [x] I have followed the guidelines in our Contributing document
- [x] This PR has a corresponding JIRA ticket
- [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
- [x] I have written new tests for your core changes, as applicable
- [x] I have successfully ran tests locally
- [x] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally

2021-04-26 05:38 UTC, ctverceles requested changes
@ernestpascual great job altering the tests and thanks for finishing up that function for @mystbrent to continue with his work. Logic looks great and tests all run on my local. Just some minor comments

What are your thoughts on implementing a best practice wherein whenever we test we adhere to the ff, which makes it easier for anyone in the team to understand what is happening (now that we're more devs):

- no "unlabeled numbers" in the values to be compared, always store a number in an `actual...` or `expected...` variable
- no "out of thin air" numbers in tests, always explain via comments or in code calculation where something came from

Following those practices, a sample test flow could be:

1. calculate some actual value, assign to `actual<variable_name>` (like `actualHALOHALOPrice`)
2. calculated expected value, assign to `expected<variable_name>` (like `expectedHALOHALOPrice`
3. compare actual vs expected value with clear err message (as you've done very well @ernestpascual )

Is this something you'd like to follow or is it overkill? FYI @bitcoinbrisbane if you have thoughts here

2021-04-26 05:38 UTC, ctverceles commented on test/halohalo.ts
>      })
@ernestpascual we can also add another test here that expects the `owner` address to have a certain HALOHALO balance (equal to the HALO tokens deposited in HaloHalo due to first time `enter` is being called but good to test this as well still)

2021-04-26 05:38 UTC, ctverceles commented on test/halohalo.ts
> +      expect(halohaloPrice, 'HALOHALO is not equal to 1').to.equal(1)
@ernestpascual is `1` supposed to be the value of `ownerHaloBal` in line 70? Moving forward let's try to avoid having numbers in the expected price and instead store it in a variable named `expectedHALOHALOPrice` or something. 

Likewise, can we rename `halohaloPrice` to `actualHALOHALOPrice`

Then can also do this `expectedHALOPrice = ownerBal` after line 70, then at this line 88 we do `expect(actualHALOHALOPrice, 'HALOHALO is not equal to 1').to.equal(expectedHALOHALOPrice)`

2021-04-26 05:38 UTC, ctverceles commented on test/halohalo.ts
> +      await haloTokenContract.mint(halohaloContract.address, parseEther('120'))
@ernestpascual can we also be very verbose about where `120` came from? Either through comments or calculating it within this code. I'm not sure how this is calculated from reading this :)

2021-04-26 05:38 UTC, ctverceles commented on test/halohalo.ts
> +      expect(
@ernestpascual is it possible to expect `halohaloPriceAfterVesting` to be compared to an actual value rather than expecting to be greater than `halohaloPrice`? Just to be air tight with our tests :)

2021-04-26 05:38 UTC, ctverceles commented on test/halohalo.ts
> +      const ownerHaloHalo = await halohaloContract.balanceOf(owner.address)
Thanks for updating the vars @ernestpascual 🙏

2021-04-26 05:38 UTC, ctverceles commented on test/halohalo.ts
> +      await haloTokenContract.mint(halohaloContract.address, parseEther('120'))
@ernestpascual same comment about the 120 up there :) can we also be very verbose about where 120 came from? Either through comments or calculating it within this code. I'm not sure how this is calculated from reading this :)

2021-04-26 05:53 UTC, ctverceles commented on contracts/Rewards.sol
> +    // minterLpRewardsRatio = _minterLpRewardsRatio;
@ernestpascual do we need these comments still?

2021-04-26 06:01 UTC, ctverceles commented on contracts/Rewards.sol
> +  function getMinterContractAddress() public view returns (address) {
maybe we can also group the view functions under the VIEW FUNCTIONS comment block and check that the other comment blocks are still organising the rest of these funcs

2021-04-26 07:31 UTC, bitcoinbrisbane commented on contracts/Rewards.sol
> +  address private constant NULL_ADDRESS =
What about 
```suggestion
  address private constant NULL_ADDRESS = address(0);
```

2021-04-26 07:32 UTC, bitcoinbrisbane commented on contracts/Rewards.sol
> +    //minterContract = _minter;
Lets remove
```suggestion
    //minterContract = _minter;
```

2021-04-26 10:39 UTC, bitcoinbrisbane commented on contracts/Rewards.sol
> +    address collateralAddress,
Maybe 
```suggestion
    address indexed collateralAddress,
```

2021-04-26 10:39 UTC, bitcoinbrisbane commented on contracts/Rewards.sol
> +    address lpAddress,
Maybe 

```suggestion
    address indexed lpAddress,
```

2021-04-26 10:40 UTC, bitcoinbrisbane commented on contracts/Rewards.sol
> +      //haloReward
```suggestion
```

2021-04-26 10:42 UTC, bitcoinbrisbane requested changes
Few suggestions

2021-04-26 12:08 UTC, mystbrent requested changes
All tests are running great! Just requested an additional real life example to the HaloHalo.getCurrentHaloHaloPrice() in the test cases.

2021-04-26 12:08 UTC, mystbrent commented on test/halohalo.ts
> +      expect(
Hi @ernestpascual thank you for doing the getCurrentHaloHaloPrice(). Can I request a more real life example of this function in the test cases? I think something similar to @ctverceles Alice, Bob example would be really great to illustrate how the logic here works. Thank you :)

2021-04-26 14:30 UTC, ernestpascual commented on test/halohalo.ts
> +      expect(
@ctverceles I added an extra test instead. I believe we still need the first test to show that it's not 1:1.

2021-04-26 14:55 UTC, ernestpascual commented on contracts/Rewards.sol
> +  address private constant NULL_ADDRESS =
thanks for this @bitcoinbrisbane !

2021-04-26 15:46 UTC, ernestpascual commented on test/halohalo.ts
> +      expect(
@mystbrent  sure!

Alice wants to check the current price of her HALOHALO tokens in terms of HALO. The HALOHALO price is determined by the ratio of the total HALO balance of the HALOHALO contract and the total supply of HALOHALO minted by the contract. For Alice to get the price of her tokens, we multiply her number of tokens by the ratio of total HALO inside the contract and total supply of HALOHALO minted. 

I hope this answers your question 😅

2021-04-26 16:40 UTC, ernestpascual commented
Updated with all the recommended changes!  ready to review again.
- broke down the old `onlyMinter()` modifier to` onlyMinter()` and `requireMinter()`
- added `requireMinter()` on functions that can be called by other parties besides the minter but need the `minterContractAddress`
- Removed the commented constructor parameters
- Delete unused comments
- deleted `@notice` of other view functions that are redundant. Left `@dev instead` 
- set `NULL_ADDRESS` to `address(0)` from @bitcoinbrisbane 's suggestion
- added indexed to address parameters of events
- changed all values as variables for the tests
- added additional testing as recommended by @ctverceles

2021-04-27 00:06 UTC, bitcoinbrisbane commented on test/halohalo.ts
> +      expect(
In "Given, When, Then" https://martinfowler.com/bliki/GivenWhenThen.html

## Scenario 1
- Given Alice has 100 HALO
- And the HALO contract has 100 HALO
- When she deposits 100 HALO 
- Then she receives 100 HALOHALO

2021-04-27 07:09 UTC, bitcoinbrisbane approved these changes
LGTM

2021-04-27 07:19 UTC, mystbrent approved these changes

2021-04-27 07:36 UTC, ctverceles approved these changes
Great work @ernestpascual ! all running on my local and changes look addressed

2021-04-27 08:16 UTC, merged