Added hardhat deploy script to easily deploy all contracts
HaloDAO/halo-rewards pull request #2
Opened 2021-03-16 12:52 UTC by schystz

Adds a hardhat deploy script for deploying the Rewards contract and other dependency contracts

2021-03-17 06:37 UTC, ernestpascual requested changes
Left some minor comments in the deploy script @schystz Looks good overall!

2021-03-17 06:37 UTC, ernestpascual commented on hardhat/scripts/deploy.js
> +}
@schystz  we need to transfer some halo to the rewards contract. we can add it after deploying the rewards contract. Right now I'm minting new tokens directly to the rewards contract:

```
  const INITIAL_MINT = 10 ** 6;
  
  await haloTokenContract.mint(
    rewardsContract.address,
    ethers.utils.parseEther((40 * INITIAL_MINT).toString())
  );
```

 I have this now. I got this from the rewards test. (https://github.com/HaloDAO/halo-rewards/blob/8d32983f0ea613b81a17ae0ed885bd0f1843ac5a/hardhat/test/reward-test.js#L17)

2021-03-17 06:37 UTC, ernestpascual commented on hardhat/scripts/deploy.js
> +  const ammLpPools = [[lpTokenContract.address, 10]]
Do we hardcode the current balancer pool address that we have now? cc: @tracyarciaga @ctverceles

2021-03-17 06:37 UTC, ernestpascual commented on hardhat/scripts/deploy.js
> +  const LpToken = await ethers.getContractFactory('LpToken')
Thinking of removing this and just add the balancer tokens instead.

You can find it on https://kovan.pools.balancer.exchange/#/pool/0x37f80ac90235ce0d3911952d0ce49071a0ffdb1e/about

2021-03-17 06:48 UTC, schystz commented on hardhat/scripts/deploy.js
> +  const LpToken = await ethers.getContractFactory('LpToken')
Agree, let me update this!

2021-03-17 06:48 UTC, schystz commented on hardhat/scripts/deploy.js
> +  const ammLpPools = [[lpTokenContract.address, 10]]
Yeah let's just hardcode the kovan balancer pools

2021-03-17 06:50 UTC, schystz commented on hardhat/scripts/deploy.js
> +}
Thanks for the catch, will add this!

2021-03-17 06:50 UTC, tracyarciaga approved these changes

2021-03-17 07:35 UTC, schystz commented
@ernestpascual updated with your suggestions! Have added 2 balancer pool addresses for the initial LP contracts.

2021-03-17 07:35 UTC, schystz commented on hardhat/scripts/deploy.js
> +  const LpToken = await ethers.getContractFactory('LpToken')
Removed

2021-03-17 07:35 UTC, schystz commented on hardhat/scripts/deploy.js
> +  const ammLpPools = [[lpTokenContract.address, 10]]
Added 2 kovan balancer pool addresses

2021-03-17 07:35 UTC, schystz commented on hardhat/scripts/deploy.js
> +}
Added the initial mint

2021-03-17 15:28 UTC, ernestpascual approved these changes
looking good. thanks james! ready to merge

2021-03-17 16:02 UTC, ernestpascual commented
Sorry, one more thing before merging. Can we add this in package.json "deploy:kovan": "npx hardhat run scripts/deploy.js --network \"kovan\""

this is the command for using the deploy script to deploy to kovan. thanks! @schystz

2021-03-18 12:57 UTC, schystz commented
@ernestpascual added the `deploy:kovan` command. Pls let me know if it looks good to you!

2021-03-18 13:09 UTC, ernestpascual approved these changes
thanks james!

2021-03-19 03:27 UTC, merged