BGM-657  Create new function in rewards contract to get all AMM pool addresses
HaloDAO/halo-rewards pull request #3
Opened 2021-03-17 09:04 UTC by schystz

2021-03-17 15:25 UTC, ernestpascual requested changes
Left some comments @schystz. Congrats on your first solidity codes!

2021-03-17 15:25 UTC, ernestpascual commented on hardhat/contracts/Rewards.sol
> +        if (ammLpPools[_lpAddress].allocPoint == 0) { // means this address is not added yet to ammLpPoolsAddresses
we can use require for validations @schystz . you can check more here https://ethereum.stackexchange.com/questions/15166/difference-between-require-and-assert-and-the-difference-between-revert-and-thro

2021-03-17 15:25 UTC, ernestpascual commented on hardhat/contracts/Rewards.sol
> +        uint8 whitelistedCount = 0;
can we fuse this into one for loop?

2021-03-17 15:25 UTC, ernestpascual commented on hardhat/contracts/Rewards.sol
> +        if (ammLpPools[_lpAddress].allocPoint == 0) { // means this address is not added yet to ammLpPoolsAddresses
also a question why did you use allocPoint over checking the mapping if it exists( `ammpLpPools[_lpAddress] = true`)?

2021-03-17 15:25 UTC, ernestpascual commented on hardhat/test/reward-test.js
> +describe('AMM dApp should be able to query some info from the Rewards contract', () => {
we can also add fail cases here. for example line 604 of Rewards.sol

2021-03-18 03:37 UTC, schystz commented on hardhat/contracts/Rewards.sol
> +        if (ammLpPools[_lpAddress].allocPoint == 0) { // means this address is not added yet to ammLpPoolsAddresses
@ernestpascual I believe require will return a fail/revert status if the condition fails, which we don't want to happen here. We are just checking if the address is already exists on `ammLpPoolsAddresses`, if it doesn't we add it otherwise we skip. But will try replacing the condition with `ammpLpPools[_lpAddress] == true` instead, looks like a better solution. Thanks!

2021-03-18 03:43 UTC, schystz commented on hardhat/test/reward-test.js
> +describe('AMM dApp should be able to query some info from the Rewards contract', () => {
Ah, actually this use case is already tested - because initially we already added `lpTokenContract` in the Rewards constructor, then there is a test on line 473 of this file that removes it, and we added it again on line 517. So basically the `lpTokenContract` address has already been added twice.

Actually line 604 of Rewards.sol is added only after I run the full test suite and realized I needed to make sure there are no duplicate lp address.

2021-03-18 03:44 UTC, schystz commented on hardhat/contracts/Rewards.sol
> +        uint8 whitelistedCount = 0;
My thoughts exactly, any other ideas? This looks ugly to me as well tbh :D

2021-03-18 05:02 UTC, ernestpascual commented on hardhat/contracts/Rewards.sol
> +        uint8 whitelistedCount = 0;
i think that is fine for now. I can't think of a better way to do it now.

2021-03-18 05:04 UTC, ernestpascual commented on hardhat/contracts/Rewards.sol
> +        if (ammLpPools[_lpAddress].allocPoint == 0) { // means this address is not added yet to ammLpPoolsAddresses
okay got this. you can ignore the test comment as well. i was thinking about testing a require statement.

2021-03-18 05:46 UTC, schystz commented on hardhat/contracts/Rewards.sol
> +        uint8 whitelistedCount = 0;
@ernestpascual went will an `address[]` instead for keeping track of the pool addresses as you suggested, looks more clean and reliable now if you would agree :D

2021-03-18 13:11 UTC, ernestpascual approved these changes
Looking good!

2021-03-19 11:19 UTC, tracyarciaga approved these changes

2021-03-19 11:57 UTC, merged