Feature/hdf 60 create update halo halo price
HaloDAO/halo-rewards pull request #9
Opened 2021-04-06 16:33 UTC by ernestpascual

## Description of Changes
- created `estimatedHaloHaloApy`, `updateHaloHaloPrice()` functions in the Halohalo contract
- created the `latestHaloHaloPrice` public variable to access the current halohalo price and the last time it was updated based on the `HaloHaloPrice` struct
- added typescript support
- modified the config file to support ts
- modified the test to support ts
- separated tests for both contracts and renamed them
- added the hardhat gas reporter to check gas estimations
- added prettier (the one we use for all)

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-60)
[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-70)

## How To Test
- reinstall packages (yarn or npm install)
- yarn run test / npm run test
- you should see all the tests passing and the gas estimation table after the tests are finished

### Developer Checklist:

- [x] I have followed the guidelines in our Contributing document
- [x] This PR has a corresponding JIRA ticket
- [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
- [x] I have written new tests for your core changes, as applicable
- [x] I have successfully ran tests locally
- [x] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally

2021-04-06 23:10 UTC, bitcoinbrisbane commented on contracts/HaloHalo.sol
> +  HaloHaloPrice public latestHaloHaloPrice;
Let's group  these at the top of the contract.

2021-04-06 23:11 UTC, bitcoinbrisbane commented on contracts/HaloHalo.sol
> +    else {
Should move this to #LN38

2021-04-06 23:11 UTC, bitcoinbrisbane commented on contracts/HaloHalo.sol
> +  // Unclocks the staked + gained Halo and burns HALOHALO
```suggestion
  // Unlocks the staked + gained Halo and burns HALOHALO
```

2021-04-06 23:12 UTC, bitcoinbrisbane commented on contracts/HaloHalo.sol
> +    halo.transfer(msg.sender, haloHaloAmount);
Maybe fire an event here?

2021-04-06 23:12 UTC, bitcoinbrisbane commented on contracts/HaloHalo.sol
> +    APY = APYProjection.div(DECIMALS);
Maybe fire an event here?

2021-04-06 23:12 UTC, bitcoinbrisbane commented on contracts/HaloHalo.sol
> +    uint256 APYProjection = haloHaloPriceChange * APYDurationRatio;
```suggestion
    uint256 APYProjection = haloHaloPriceChange.mul(APYDurationRatio);
```

2021-04-06 23:13 UTC, bitcoinbrisbane commented on contracts/HaloHalo.sol
> +      updateIntervalDuration.mul(DECIMALS).div(31536000);
Whats that number?

2021-04-06 23:14 UTC, bitcoinbrisbane requested changes
Few minor changes

2021-04-07 02:21 UTC, ernestpascual commented on contracts/HaloHalo.sol
> +      updateIntervalDuration.mul(DECIMALS).div(31536000);
number of seconds in a year

2021-04-07 02:25 UTC, ernestpascual commented on contracts/HaloHalo.sol
> +    halo.transfer(msg.sender, haloHaloAmount);
i did not touch this code since the one who made this forked it directly to the sushibar contract. but i'm good to add actually if everyone agrees!

2021-04-07 02:37 UTC, ernestpascual commented
@bitcoinbrisbane resolved most of the comments and left the ones for discussion.

2021-04-07 23:26 UTC, bitcoinbrisbane approved these changes

2021-04-08 00:53 UTC, tracyarciaga approved these changes

2021-04-08 02:29 UTC, merged